name: Go
on: [push, pull_request]
jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Run cassandra
      run: |
         docker run --name mycassandra -d -p 9042:9042 -e CASSANDRA_LISTEN_ADDRESS=127.0.0.1 cassandra:3.11

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Go - Modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: CI
      uses: untillpro/ci-action@master
      with:
        organization: 'heeus'
        token: ${{ secrets.REPOREADING_TOKEN }}
        codecov-token: ${{ secrets.CODECOV_TOKEN }}
  
    - name: Check copyright
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/check_copyright.sh | bash -s "$(go env GOPATH)"
  
    - name: Linters
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/gbash.sh | bash -s "$(go env GOPATH)"
